fix

diff --git a/.github/actions/run_tests/action.yml b/.github/actions/run_tests/action.yml
--- a/.github/actions/run_tests/action.yml
+++ b/.github/actions/run_tests/action.yml
@@ -11,14 +11,14 @@ runs:
         cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all-tests -j$(nproc)
         echo "::group::Build Tests done"
 
-    #- name: Run CTest
-    #  shell: bash
-    #  run: |
-    #    echo "::group::Run CTest"
-    #    cd build 
-    #    if ! ctest -C ${{env.BUILD_TYPE}} -j$(nproc) --output-on-failure 
-    #    then
-    #      echo "::error::Tests failed"
-    #      ctest --output-on-failure --rerun-failed
-    #    fi
-    #    echo "::group::Run CTest done"
+    - name: Run CTest
+      shell: bash
+      run: |
+        echo "::group::Run CTest"
+        cd build 
+        if ! ctest -C ${{env.BUILD_TYPE}} -j$(nproc) --output-on-failure 
+        then
+          echo "::error::Tests failed"
+          ctest --output-on-failure --rerun-failed
+        fi
+        echo "::group::Run CTest done"
